# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8daba68502b28aaa8562ffabd6a2879b661f8b3beeb43939f6d63453ba5f9cc11f17d0208c69428facee17d242001089160b953b0f43698b95cbb7e3d5051d

test:
  secret_key_base: c5db11c5f8eab6609e9d7b802422c205206d691561bd34a17e4543e5556b2a6af2d0e025c0c4b3c880f244e6d3c1f25d1178f8726fc437bb31d41c17e643beb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
